version: "3.8"
services:
  lamdera:
    build: .
    image: lamdera-dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - LAMDERA_ENV=development
    command: 
     [
        "sh",
        "-c",
        "lamdera rebuild && \
         watchexec --restart --exts elm --watch ./src -- lamdera rebuild & \
         lamdera live --port 3000"
      ]
    # command:  ["sh", "-c", "watchexec -e elm -w src -- lamdera rebuild & lamdera live --port 3000"]
    # ["lamdera", "live", "--port", "3000"]
      # ["sh", "-c", "tail -f /dev/null"] # 