version: "3.8"
services:
  lamdera:
    build: .
    image: lamdera-dev
    container_name: lamdera
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: ["watchexec", "--poll", "1s", "-r", "-e", "elm", "-w", "src", "--", "./restart-lamdera.sh"]
